### ISSUE TITLE
大佬你好 今天有更新了一次版本 你的mod崩溃了 可以更新一下么

### ISSUE THREAD

**Issue by qiangyang051** [undancer/oni-mods#1]
**前提条件**

- [x] 我确保所运行的游戏是最新版 
- [x] 我使用的是代码库中最新的版本
- [x] 我检查过游戏日志文件，并确定是该mod发生的错误
- [x] 我检查过源码、文档或者社区，并没有找到答案
- [x] 我检查过上报的问题未曾提交过

**描述问题**

**游戏环境**
 - 操作系统： [比如 Windows, macOS]
 - 游戏平台： [比如 Steam, 某平台，盗版]
 - 游戏版本： [比如 RP-383949]

**附加信息**

**日志文件**

日志文件会生成在以下目录
- Windows: `%USERPROFILE%\AppData\LocalLow\Klei\Oxygen Not Included\output_log.txt`
- Linux: `$home/.config/unity3d/Klei/Oxygen Not Included/Player.log`
- MacOS: `$home/Library/Logs/Unity/Player.log`

**Comment by KirinRyuuri** [comment]
单开这个mod没问题，你看下是不是和其他mod冲突了

**Comment by undancer** [comment]
> 单开这个mod没问题，你看下是不是和其他mod冲突了

日志文件呢？

**Comment by KirinRyuuri** [comment]
> > 单开这个mod没问题，你看下是不是和其他mod冲突了
> 
> 日志文件呢？

我的游戏没崩溃
是反馈一下 @qiangyang051 可能需要进一步排查一下是不是这个mod造成的问题

**Comment by undancer** [comment]
> > > 单开这个mod没问题，你看下是不是和其他mod冲突了
> > 
> > 
> > 日志文件呢？
> 
> 我的游戏没崩溃
> 是反馈一下 @qiangyang051 可能需要进一步排查一下是不是这个mod造成的问题

嗯，我发现了。可能他是本体版，没有购买DLC。在早期的更新中这情况的确会崩溃。但现在已经修复了。
